date_ranges:
  Transaction Date:
    min: "2022-01-01"
    max: "2024-12-31"

outlier_thresholds:
  Quantity:
    min: 1
    max: 20
  Price Per Unit:
    min: 1
    max: 50

skip_columns:
  - Transaction ID

imputation:
  numeric: knn       # options: knn, median, mean
  categorical: mode  # options: mode, constant
  text: constant     # constant fill value
